import type { DialConfig } from "dialkit";

export const syncSettingsDialConfig = {
  Section: {
    gap: 16,
    innerGap: 12,
    panelPaddingX: 24,
    panelPaddingY: 16,
    sectionPaddingX: 0,
  },
  ChoiceCard: {
    paddingX: 12,
    paddingY: 12,
    gap: 12,
    borderRadius: 10,
    iconSize: 37,
    iconInner: 18,
    iconRadius: 12,
    titleSize: 13,
    subtitleSize: 12,
    activeBg: "light-dark(#fafafa, #1a1a1a)",
    activeBorder: "light-dark(#ececec, #333)",
    idleBorder: "light-dark(#ececec, #333)",
    iconBg: "light-dark(#2a2a2a, #e0e0e0)",
    iconActiveBg: "light-dark(#2a2a2a, #e0e0e0)",
    iconColor: "light-dark(#adadad, #666)",
    iconActiveColor: "light-dark(#ffffff, #1a1a1a)",
  },
  FieldCard: {
    paddingX: 14,
    paddingY: 14,
    borderRadius: 10,
    gap: 12,
    inputGap: 6,
    inputPaddingX: 10,
    inputPaddingY: 6,
    inputBorderRadius: 8,
    inputFontSize: 13,
    bg: "var(--muted)",
    borderColor: "var(--border)",
    labelSize: 12,
    noteSize: 11,
    labelWeight: 500,
    labelColor: "var(--foreground)",
  },
  Dropdown: {
    height: 36,
    borderRadius: 8,
    fontSize: 12,
    paddingX: 12,
    bg: "light-dark(#fafafa, #1a1a1a)",
    borderColor: "var(--input)",
    width: -1,
    menuBg: "var(--popover)",
    menuBorder: "var(--border)",
    itemHoverBg: "light-dark(#f6f6f6, #2a2a2a)",
    itemPaddingX: 8,
    itemPaddingY: 6,
    itemGap: 8,
    itemFontSize: 13,
    checkSize: 12,
  },
  Title: {
    paddingTop: 24,
    paddingBottom: 4,
    paddingLeft: 24,
    paddingRight: 24,
    gap: 8,
    titleSize: 18,
    descSize: 12,
  },
  Footer: {
    paddingTop: 16,
    paddingBottom: 16,
    paddingLeft: 24,
    paddingRight: 24,
    gap: 8,
    bg: "light-dark(#fafafa, #1a1a1a)",
    buttonPaddingX: 16,
    buttonPaddingY: 10,
    buttonBorderRadius: 10,
  },
  CloseButton: {
    iconColor: "light-dark(#666, #999)",
    bg: "light-dark(transparent, transparent)",
    hoverBg: "light-dark(#ebebeb, #333)",
  },
  StatusBadge: {
    fontSize: 12,
    paddingX: 10,
    paddingY: 4,
    borderRadius: 8,
    successBg: "color-mix(in srgb, var(--success) 12%, transparent)",
    successColor: "var(--success)",
    warnBg: "color-mix(in srgb, var(--warning) 12%, transparent)",
    warnColor: "var(--warning)",
    errorBg: "color-mix(in srgb, var(--destructive) 12%, transparent)",
    errorColor: "var(--destructive)",
    idleBg: "var(--muted)",
    idleColor: "var(--muted-foreground)",
  },
} satisfies DialConfig;
